# Generated by Django 3.0.8 on 2021-01-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen descriptiva')),
                ('description', models.TextField()),
                ('unit', models.CharField(blank=True, max_length=12, verbose_name='Unidad de medida')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['title'],
            },
        ),
    ]
