# Generated by Django 3.0.8 on 2021-01-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_adress', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingadress',
            options={'ordering': ['created_at'], 'verbose_name': 'Dirección de envio', 'verbose_name_plural': 'Direcciones de envio'},
        ),
    ]
