# Generated by Django 3.0.8 on 2021-01-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_adress', '0002_auto_20210114_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingadress',
            options={'ordering': ['default', 'created_at'], 'verbose_name': 'Dirección de envio', 'verbose_name_plural': 'Direcciones de envio'},
        ),
    ]
