# Generated by Django 3.0.8 on 2021-01-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_adress', '0003_auto_20210114_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='reference',
            field=models.CharField(max_length=100, verbose_name='Referencia'),
        ),
    ]
